# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NotesApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  pod 'RealmSwift'
  pod 'Alamofire'
  pod 'SwiftyJSON'
  pod 'Swinject'
  pod 'SwinjectStoryboard'
  
  # Pods for NotesApp

  target 'NotesAppTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
